### DISCUSSION TITLE
Problem with keycloak login url

### DISCUSSION THREAD

**Discussion by ThanKarab** [ch4mpy/spring-addons#139] [Q&A]
Hello @ch4mpy ,

I have keycloak server 15 running, dockerized with jboss containers and a web app backend that was running with very versions of the keycloak adapter and spring in general.

I am currently migrating the web app backend to latest versions, spring 3 etc and as you already know, I cannot keep using the keycloak adapters.

I am following this tutorial, https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/servlet-client, but I cannot seem to get the login url to work properly.

The web app backend is a REST api but it was serving as the client as well previously and would like to keep it that way. 

My current configuration:
application.yml
```
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8095/auth/realms/MIP
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-name: CN
            client-id: CI
            client-secret: CS
            provider: keycloak
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8095/auth/realms/MIP
```

My security config:
```
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfiguration {

    @Value("#{'${authentication.enabled}'}")
    private boolean authenticationEnabled;

    @Bean
    SecurityFilterChain clientSecurityFilterChain(HttpSecurity http, ClientRegistrationRepository clientRegistrationRepo) throws Exception {
        http.oauth2Login(withDefaults());
        http.authorizeHttpRequests(ex -> ex
                .requestMatchers("/login/**", "/oauth2/**", "/actuator/**").permitAll()
                .anyRequest().authenticated());
        return http.build();
    }
}
```

The result of the `GET http://172.17.0.1/services/sso/login` request is a redirect to `http://172.17.0.1/services/oauth2/authorization/keycloak` where I get the following: 
```
{"statusCode":404,"message":"Cannot GET /oauth2/authorization/keycloak","error":"Not Found"}
```

I am still using the keycloak server 15, don't know if that's related.

Any idea what I am doing wrong?
