### DISCUSSION TITLE
Multi-tenant OAuth2 login (authorization-code flow) from Single Page Applications

### DISCUSSION THREAD

**Discussion by lucapino** [ch4mpy/spring-addons#175] [Q&A] [answered]
Hi all!

I'm trying to migrate a configuration for multitenant transparent login using Keycloak Adapters with Spring Boot 2 to simple Spring Security 6.

I've implemented a solution based on an HeaderBasedConfigResolver that permits redirect to the correct keycloak realm URL, based on an header prevously set, following this article -> https://www.czetsuyatech.com/2020/11/spring-boot-multi-tenancy-with-keycloak.html

With this implementation I implement an HeaderBasedConfigResolver that resolve the configuration based on a specific header so the Keycloak Adapter can redirect to the correct login URL (based on the realm name).

Now, Keycloak Adapters doesn't work anymore with Spring Boot 3, so I was trying to find an alternative solution.

I don't find anything that can fit my needs, but only a solution that prompts for the authorization server to use...

So I'm asking an advice

BR
Luca Tagliani

**Comment by ch4mpy** [comment]
If you are in the case of "static" mutli-tenancy (you know at startup which issuers you want to trust), a look at the BFF tutorial and more specifically at the [GatewayController](https://github.com/ch4mpy/spring-addons/blob/master/samples/tutorials/bff/backend/with-c4-soft/bff-c4/src/main/java/com/c4_soft/dzone_oauth2_spring/c4_bff/GatewayController.java).

The idea behind this implementation is that a REST endpoint exposes the list of URIs to initiate user authentication (DTO is composed of an URI and a `label` which might be pretty close to the value of the header you used so far). There is one entry for each client "registration" with authorization-code flow and as you should have one such registration for each issuer.

This achieves what you want with just one small difference: the frontend uses a different URI for each issuer (provided by the Spring OAuth2 client) without any specific header, instead of a unique URI with a different header for each issuer.

**Reply by lucapino** [reply]
Thanks @ch4mpy for the quick answer, but if you don't mind I will try to describe more in detail my original flow, because I don't think I was clear.

First of all, my tenants are surely statically defined also because the creation of a new tenant cannot be performed at runtime (involves multiple components/DB so this is not the case)

So, my original flow is as follow:
- user browse the URL of the GUI app (e.g. tenant1.example.com)
- the URL is resolved by an NGINX instance that sets a custom header to identify the tenant (it may be different from the subdomain in the URL) then proxy the request to the real SB app
- the SB app, using a custom filter extracts the <tenant_name> and sets the correct configuration on Keycloak Adapter
- the user's browser is redirected to the specific Keycloak URL (e.g. keycloak.example.com/auth/realms/<tenant_name>) for the authentication
- the user authenticate using Keycloak login page and then is redirected back to the app with the Bearer token in the Authentication header

The header set by NGINX is needed at application level to manage the multitenancy (not only for authentication purposes), so I cannot remove it

As you can see, from the user's point of view the flow is automatic (the user doesn't have to choose anything and is redirected to the correct URL of Keycloak as if it is the only one configured)

If I understood well, your solution provides a URL to call to choose the issuer and if the issuer is the only one it will redirect directly to the correct login URL.

I want to avoid to call a custom URL and act as if there is only an authentication server.

Forgive me if this is already understood (or even less clear than before :wink: )

BR
Luca Tagliani

**Comment by ch4mpy** [comment]
@lucapino as a preamble, apparently, your Angular app is configured as a "public" OAuth2 client, which has been considered a worst practice for years. [Spring Security team published about that 2-3 years ago](https://github.com/spring-projects/spring-authorization-server/issues/297#issue-896744390) and you might find posts from other security experts even before that. Requests from your Angular app should be authorized with sessions (and CSRF protection), not with tokens. You should probably use a middleware (a **B**ackend **F**or **F**rontend, aka BFF) between your Angular app and your Spring resource servers to translate from session based security to token based security. But all that is already explained [in the tutorial I linked in my preceding comment](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/bff).

Back to your question: apparently you did not understand the solution in my preceding comment, so I'll try to be very specific with samples.

Let's say that you host two sites: 
- `https://www.luca.it`
- `https://www.tagliani.it`

Let's now say that each site has it's own realm with respectively as issuers:
- `https://sso.lucapino.it/realms/luca`
- `https://sso.lucapino.it/realms/tagliani`

Let's also say that, as BFF, you have a `spring-cloud-gateway` instance configured with:
- `spring-boot-starter-oauth2-client` and `oauth2Login()` to handle OAuth2 authorization-code flow and store tokens in sesssions
- `TokenRelay=` filter to replace session cookie with the access token in session before forwarding a request from the frontend to a resource server
- `StripPrefix=2` filter on route(s) intercepting `/bff/v1/**` and forwarding to resource server(s), stripping the `/bff/v1` prefix
- Spring Security OAuth2 "registrations" for your two issuers
```yaml
user-name-attribute: preferred_username
luca-issuer: https://sso.lucapino.it/realms/luca
luca-client-id: luca-bff
luca-client-secret: change-me
tagliani-issuer: https://sso.lucapino.it/realms/tagliani
tagliani-client-id: tagliani-bff
tagliani-client-secret: change-me

spring:
  security:
    oauth2:
      client:
        provider:
          luca:
            issuer-uri: ${luca-issuer}
            user-name-attribute: ${user-name-attribute}
          tagliani:
            issuer-uri: ${tagliani-issuer}
            user-name-attribute: ${user-name-attribute}
        registration:
          luca:
            provider: luca
            client-id: ${luca-client-id}
            client-secret: ${luca-client-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - offline_access
          tagliani:
            provider: tagliani
            client-id: ${tagliani-client-id}
            client-secret: ${tagliani-client-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - offline_access
```

Last, let's consider that you have a reverse-proxy with following routing with a single BFF instance and 2 distinct Angular apps served from nginx containers or dev-servers or whatever:
- `https://www.luca.it/ui/**` => 1st Angular app that we'll call `luca-ui`
- `https://www.luca.it/login-options` => BFF
- `https://www.luca.it/oauth2/authorization/**` => BFF
- `https://www.luca.it/login/oauth2/code/**` => BFF
- `https://www.luca.it/bff/v1/**` => BFF
- `https://www.tagliani.it/ui/**` => 2nd Angular app that we'll call `tagliani-ui`
- `https://www.tagliani.it/login-options` => BFF
- `https://www.tagliani.it/oauth2/authorization/**` => BFF
- `https://www.tagliani.it/login/oauth2/code/**` => BFF
- `https://www.tagliani.it/bff/v1/**` => BFF

Now, on the BFF (which holds the OAuth2 client configuration and is responsible for driving the authorization-code flow), you expose a `/login-options` endpoint listing options for users to login. This endpoint could answer something like
```json
{
  "luca": "https://www.luca.it/oauth2/authorization/luca",
  "tagliani": "https://www.tagliani.it/oauth2/authorization/tagliani"
}
```

All the `luca-ui` has to do to authenticate a user is calling `https://www.luca.it/login-options` to retrieve the login options offered by the BFF and then follow to the URI associated to `luca` in the payload => **no need to prompt the user for that!**

Of course, if you already have a header on the frontend with an identifier of the issuer or registration you want to use with that frontend, you can send it along with the `/login-options` request and implement the Spring endpoint to return only the login options associated with that issuer or registration.

In any case, your Angular app should be ready to get:
- 0 option (display an error?). This might happen with misconfiguration for instance.
- exactly 1 option (follow redirect without any prompt?). This should be the most frequent case.
- more than 1 options (use business logic or static configuration to filter entries and fallback to the 0 or 1 option behaviors? Prompt the user which to use?). This can happen when you configure more than one registrations with authorization-code for a given issuer (different OAuth2 client, different scopes, ...), but this is pretty rare.

I hope you can adapt by yourself the use-case above if you prefer to use `https://www.lucapino.it/luca/**` and `https://www.lucapino.it/tagliani/**` instead of `https://www.luca.it/ui/**` and `https://www.tagliani.it/ui/**` for your Angular apps or if you want to add Keycloak to the services behind the reverse-proxy (to easily display login forms in iframes for instance).

On the resource server side, this is just standard "static" multi-tenancy configuration: requests will arrive from the BFF with tokens containing either `https://sso.lucapino.it/realms/luca` or `https://sso.lucapino.it/realms/tagliani` as issuer and the resource server should accept both. `spring-addons` supports that out of the box.
