### DISCUSSION TITLE
How to configure Azure AD B2C ?

### DISCUSSION THREAD

**Discussion by ch4mpy** [ch4mpy/spring-addons#198] [Q&A] [answered]
Created from [this other question](https://github.com/ch4mpy/spring-addons/discussions/197#discussioncomment-8806523) asked by @veganchamp.

I'm getting the exception below
(I've replaced real tenantId with TID)

```
Caused by: java.lang.IllegalStateException: The Issuer "https://sys-login.lvgig.co.uk/TID/" provided in the configuration metadata did not match the requested issuer "https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3/"
at org.springframework.util.Assert.state(Assert.java:97)
at org.springframework.security.oauth2.client.registration.ClientRegistrations.withProviderConfiguration(ClientRegistrations.java:246)
```
The issuer-uri looks good: `https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3/.well-known/openid-configuration`
giving:
```json
{
"issuer": "https://sys-login.lvgig.co.uk/TID/",
"authorization_endpoint": "https://sys-login.lvgig.co.uk/TID/b2c_1a_rpsaveqa3/oauth2/authorize",
...
}
```

**Comment by ch4mpy** [comment, marked as answer]
Spring Boot configuration properties should be set as follow:
- just `issuer-uri` with what you find in tokens as `iss` claim (exactly, even case and trailing slash, if any, are important), but **only if OpenID configuration can be found by just adding `.well-known/openid-configuration` to it** (no added or modifiedpath segment in between)
- `jwk-set-endpoint`, `authorization-uri`, `token-uri` and `user-info-uri` with what you find **in OpenID configuration** (what you get from `https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3/.well-known/openid-configuration`)

Setting just `issuer-uri` is possible only if the OpenID configuration is available from `${issuer-uri}/.well-known/openid-configuration` (or `${issuer-uri}.well-known/openid-configuration` if `issuer-uri` ends with a `/`). In that case,  Spring auto-configures `jwk-set-endpoint`, `authorization-uri`, `token-uri` and `user-info-uri` with what it finds in the OpenID configuration.

But in your case, it seems that a path segment is missing in `issuer-uri` for Spring auto-configuration to be possible (it seems to be `https://sys-login.lvgig.co.uk/TID/` and not `https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3`). In such a case, you should provide with all properties in the conf.

Please double check one of your access token `iss` claim (you can decode it with a tool like [https://jwt.io](https://jwt.io) if it's a JWT or send it to the introspection endpoint, whatever the format).

If the access token `iss` claim is `https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3` or `https://sys-login.lvgig.co.uk/TID/B2C_1A_RPSaveQA3/`, your conf should look like:
```yaml
tenant: change-me
# double check that
# - this value is EXACTLY what you get as "iss" claim in tokens (even case and trailing slash are important)
# - OpenID configuration is available from https://sys-login.lvgig.co.uk/${tenant}/B2C_1A_RPSaveQA3/.well-known/openid-configuration
azure-issuer: https://sys-login.lvgig.co.uk/${tenant}/B2C_1A_RPSaveQA3/

spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad-b2c:
            issuer-uri: ${azure-issuer}
            # other provider properties are auto-configured by Spring Security from the OpenID configuration
```

If the OpenID configuration cannot be fetched by appending `.well-known/openid-configuration` to the URI found as `iss` claim value in tokens, then your conf should look something like that:
```yaml
tenant: change-me
# Double-check this values against what you actually get from .well-known/openid-configuration
azure-authorization-endpoint: https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize
azure-token-endpoint: https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token
azure-jwks-endpoint: https://login.microsoftonline.com/${tenant}/discovery/v2.0/keys

spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad-b2c:
            jwk-set-uri: ${azure-jwks-endpoint}
            authorization-uri: ${azure-authorization-endpoint}
            token-uri: ${azure-token-endpoint}
```
