### DISCUSSION TITLE
Which is the role of "username-claim: preferred_username" ?

### DISCUSSION THREAD

**Discussion by rgambelli** [ch4mpy/spring-addons#204] [Q&A] [answered]
Hi,

I would like to know the specific role of the property:

```
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: https://oidc.c4-soft.com/auth/realms/master
          username-claim: preferred_username
```

In the code tutorial hosted on baledung I don't find it, [here is the bff application.yml](https://github.com/eugenp/tutorials/blob/master/spring-security-modules/spring-security-oauth2-bff/backend/bff/src/main/resources/application.yml) but I'm pretty sure that some times ago there was, in my code there is and I was inspired by the tutorial.

Maybe it's a concept related only to applications acting as resource-server ?
What if bff is either a client or a resource-server like in my scenario, do I need it?

I saw that if the value is $.preferred_username (with starting dollar) then I receive this error:
`o.s.s.w.s.a.AuthenticationWebFilter     : Authentication failed: [invalid_user_info_response] An error occurred reading the UserInfo response: Missing attribute '$.preferred_username' in attributes (lambda$authenticate$8 AuthenticationWebFilter.java 128)`

while if the value is _preferred_username_  then the flow is ok.

Thanks as always for the explanation, bye
