### DISCUSSION TITLE
Ping Identity tokens validation (https://auth.pingone.com/)

### DISCUSSION THREAD

**Discussion by naruraghavan** [ch4mpy/spring-addons#216] [Q&A] [answered]
Here is my spring addon config:

**BFF:**

```
spring:
  security:
    oauth2:
      client:
        registration:
          gas:
            client-id: ${CLIENT_ID_INT}
            client-secret: ${CLIENT_SECRET_INT}
            provider: gas
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - phone
              - job_title
              - scoped_entitlement
              - authorization_group
              - entitlement_group
              - organizational_data
              - supervisor
              - group_type
        provider:
          gas:
            issuer-uri: ${ISSUER_URI_INT}
            authorization-uri: ${ISSUER_URI_INT}/as/authorization.oauth2
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${ISSUER_URI_INT}
            authorities:
              - path: authorities
                prefix: "ROLE_"
            aud: ${audience}
        # SecurityFilterChain with oauth2Login() (sessions and CSRF protection enabled)
        client:
          client-uri: ${client_uri}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout
            - /whoami
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
          csrf: cookie-accessible-from-js
          post-logout-redirect-host: ${reverse_proxy_uri}
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          back-channel-logout:
            enabled: true
        # SecurityFilterChain with oauth2ResourceServer() (sessions and CSRF protection disabled)
        resourceserver:
          permit-all:
            - /login-options
            - /error
            - /v3/api-docs/**
            - /swagger-ui/**
            - /actuator/health/readiness
            - /actuator/health/liveness

```

**Resource Server:**

```
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${ISSUER_URI_INT}
            username-claim: sub
          - authorities:
              - path: authorities
                prefix: "ROLE_"
            aud: aud
        resourceserver:
          permit-all:
            - /token
            - /me
            - /v3/api-docs/**
            - /swagger-ui/**
            - /actuator/health/readiness
            - /actuator/health/liveness
```

1. How do I know to specify the JSON path? The spring OAuth module initiates the auth flow and gives me an OidcUser object mapping of the attributes I receive from my auth server.
2. The TokenRelay= generates an invalid Bearer token. No dots in the token resulting in JWS-SET cannot be retrieved error message at the resource server.
3. I tried creating a bearer token myself with all the attributes needed, but it resulted in an invalid signature at the resource server.
4. I tried different permutations to arrive at:
- authorities:
   - path: authorities
      prefix: "ROLE_"

but this does not work because I do not know where to go next.

All in all, I am stuck. Please advise.

**Comment by ch4mpy** [comment, marked as answer]
> The `TokenRelay=` generates an invalid Bearer token

This token is a **valid opaque token** (not a JWT), what Ping Identity calls a _token reference_. There is no chance that a JWT decoder can validate it and that's why you get a `401`.

You could use introspection instead of JWT decoding, but this would have a serious impact on your system's efficiency and scalability. I strongly advise that you contact Ping Identity support to get help configuring your authorization server to issue JWTs as access tokens (instead of token references).

> How do I know to specify the JSON path?

- use an online evaluator [like this one](https://jsonpath.com/). Most have links to some documentation about syntax
- when configuring a resource server, get the JSON payload by decoding an access JWT (use a tool like Postman to get a token and then [https://jwt.io](https://jwt.io) to decode it)
- when configuring an OAuth2 client with `oauth2Login` (like a BFF), get the payload from an ID token

**Reply by naruraghavan** [reply]
Thanks for the quick response. I did not expect that. Impressed!

"gas" stands for global authentication service from my company using Ping Identity IDP. For some reason, the `userinfo` endpoint always returns null. I do see IDToken and all the other attributes in the payload. I'll do some digging with the info you gave me. I will come back if anything. Thanks a bunch. If this works, your work will simplify several boilerplate filters and handlers to just a few lines of `yml` entries.

**Reply by ch4mpy** [reply]
According to Ping Identity docs, [they issue JWTs](https://apidocs.pingidentity.com/pingone/main/v1/api/#access-tokens-and-id-tokens). You can find here and there (Google searches about Ping Federate) references to access token (opaque) references and JWTs. Apparently, getting one or the other is a matter of client configuration on the authorization server.

According to the same doc, they don't ask for an `aud` (audience) parameter for authorization request. So you can remove that from your yaml. You can remove the `authorization-uri` too: it listed in the OpenID configuration (check in the payload of [${ISSUER_URI_INT}/.well-known/openid-configuration](https://auth.pingone.com/5caa81af-ec05-41ff-a709-c7378007a99c/as/.well-known/openid-configuration) which should be publicly accessible).

Double check that your `${ISSUER_URI_INT}` is looking something like
- if using their cloud offers, `https://auth.pingone.com/5caa81af-ec05-41ff-a709-c7378007a99c/as` 
- otherwise, whatever is listed in the OpenID configuration as `issuer` (OpenID configuration is exposed as `${issuer}/.well-known/openid-configuration`, so search a bit around if it doesn't work immediately with what you have configured as `${ISSUER_URI_INT}` so far)

Enable DEBUG logs and share your BFF logs after a login attempt.
```yaml
logging:
  level:
    org:
      springframework:
        security: DEBUG
```

Also, once you are sure about the conf, get access and ID tokens using Postman and post the decoded payloads (as I don't want to access your resource servers, I don't need the signed encoded strings, I just need the JSON payloads to see structure and the issuer value it contain)

I don't see the gateway conf, can you add it?

Last this `/token` endpoint on the resource server looks very suspicious: it is a key point of the BFF pattern to hide tokens from the "outside".

**Comment by naruraghavan** [comment]
Access token: `0001iRy2klwuLmVdUPjTGdIQz5uw`
Id token decoded (I have redacted the values, but the ISS value matches ISSUER_URI_INT)

```
{
  "sub": "...",
  "aud": "...",
  "jti": "uUlU937Qltwzr4S4tyvy7C",
  "iss": "...",
  "iat": 1719102363,
  "exp": 1719103263,
  "auth_time": 1719101358,
  "acr": "gas:strong",
  "country": "US",
  "global_cost_center_source": "...",
  "company_identifier": "...",
  "group_type": "0",
  "business_field": "...",
  "basic_start_authorization": "true",
  "updated_at": 20240622,
  "department_description": "...",
  "department": "...",
  "working_company_id": "...",
  "email": "...",
  "postal_address": "...",
  "business_category": "..",
  "global_cost_center": "...",
  "email_verified": true,
  "phone_number_verified": false,
  "given_name": "...",
  "cost_center": "...",
  "name": "....",
  "phone_number": "...",
  "family_name": "....",
  "supervisor": "..",
  "position_id": "...",
  "pi.sri": "VB4Ej2cJ3w2MMOA6UGWwidGyGYA.ZW0y",
  "sid": "VB4Ej2cJ3w2MMOA6UGWwidGyGYA.ZW0y"
}
```

**Comment by naruraghavan** [comment]
I added the `/token` endpoint to a thymeleaf page to see what happened. Since there is a problem with token validation at the resource server, I always get 401—an invalid bearer token. I will remove this route and the page after testing.

**Comment by naruraghavan** [comment]
here is the GW config:

```
  cloud:
    gateway:
      routes:
        - id: bff
          uri: ${resource_server_uri}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
            - SaveSession
            - StripPrefix=1
 
```
