### DISCUSSION TITLE
Why is my request unauthorized when routed with `TokenRelay=` on a BFF with `spring-addons-starter-oidc`?

### DISCUSSION THREAD

**Discussion by intrepidtechnology** [ch4mpy/spring-addons#237] [Q&A] [answered]
Hi there,

I've created a OAuth2 BFF with the spring-addons-starter-oidc, with Angular front-end, following Jerome's example project.

When I create a function on the controller with @Preauthorise, the system fails with 401 Unauthorized, despite the test user having the correct permissions.
When I disable @PreAuthorize, I can call the API without any issues.

Any help will be highly appriciated 

Here is my code:

Proxy:
=======================================================
```
scheme: http
hostname: 192.168.85.60
reverse-proxy-port: 7080
angular-port: 4201
angular-prefix: /angular-ui
angular-uri: http://${hostname}:${angular-port}${angular-prefix}
authorization-server-port: 8080
authorization-server-prefix: /auth
authorization-server-uri: ${scheme}://${hostname}:${authorization-server-port}${authorization-server-prefix}
bff-port: 7081
bff-prefix: /bff
bff-uri: ${scheme}://${hostname}:${bff-port}

server:
  port: ${reverse-proxy-port}
  ssl:
    enabled: false

spring:
  application:
     name: reverse-proxy-service 
     
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
      # SPAs assets
      - id: angular-ui
        uri: ${angular-uri}
        predicates:
        - Path=${angular-prefix}/**
 
      # Authorization-server
      - id: authorization-server
        uri: ${authorization-server-uri}
        predicates:
        - Path=${authorization-server-prefix}/**
      
      # Proxy BFF
      - id: bff
        uri: ${bff-uri}
        predicates:
        - Path=${bff-prefix}/**
        filters:
        - StripPrefix=1
```
     
BFF:
===================================================

```
scheme: http
hostname: 192.168.85.60
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/intrepid
client-id: intrepid-technology
client-secret: u48jMzjhtby9eX8FCUN3mNTApZgEru5Z
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
bff-port: 7081
bff-prefix: /bff
resource-server-port: 7082
audience: 

querymanagercommand-server-port: 7084

server:
  port: ${bff-port}
  ssl:
    enabled: false
  reactive:
    session:
      cookie:
        name: SESSION_${spring.application.name}


spring:
  application:
        name: bff-service
  security:
    user:
      name: root
      password: s3cr3t
      roles:
      - SYSTEM
    oauth2:
      client:
        provider:
          intrepid:
            issuer-uri: ${issuer}
        registration:
          intrepid:
            provider: intrepid
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid,profile,email,offline_access
  
  cloud:
    gateway:
      routes:
      - id: bff
        uri: ${scheme}://${hostname}:${resource-server-port}        
        predicates:
        - Path=/api/**
        filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession
        - StripPrefix=1

      #Query Manager
      - id: querymanagercommandservice
        uri: http://192.168.85.60:7084
        predicates:
          - Path=/querymanagercommand/api/**
        filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          - TokenRelay=
          - SaveSession
          - StripPrefix=1
      - id: querymanagerqueryservice
        uri: http://192.168.85.60:7085
        predicates:
          - Path=/querymanagerquery/api/**
        filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          - TokenRelay=
          - SaveSession
          - StripPrefix=1
      
com:
  c4-soft:
    springaddons:
      oidc:
        # Trusted OpenID Providers configuration (with authorities mapping)
        ops:
        - iss: ${issuer}
          authorities:
          - path: ${authorities-json-path}
          aud: ${audience}
        # SecurityFilterChain with oauth2Login() (sessions and CSRF protection enabled)
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
          - /api/**
          - /login/**
          - /oauth2/**
          - /logout/**
          permit-all:
          - /api/**
          - /login/**
          - /oauth2/**
          - /logout/connect/back-channel/intrepid
          post-logout-redirect-host: ${hostname}
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          back-channel-logout:
            enabled: true
            # internal-logout-uri: ${reverse-proxy-uri}${bff-prefix}/logout
            # should work too,  but there is no reason to go through the reverse proxy for this internal call
            internal-logout-uri: ${scheme}://${hostname}:${bff-port}/logout
        # SecurityFilterChain with oauth2ResourceServer() (sessions and CSRF protection disabled)
        resourceserver:
          permit-all:
          - /login-options
          - /error
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness

```

Resource Server:
================================
```
scheme: http
hostname: 192.168.85.60
reverse-proxy-port: 7080
reverse-proxy-uri: '${scheme}://${hostname}:${reverse-proxy-port}'
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/intrepid
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 7082
audience: null

server:
  port: '${resource-server-port}'
  ssl:
    enabled: false
  reactive:
    session:
      cookie:
        name: 'SESSION_${spring.application.name}'
        
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: '${issuer}'
          username-claim: '${username-claim-json-path}'
          authorities:
          - path: '${authorities-json-path}'
          aud: '${audience}'
        resourceserver:
          permit-all:
          - /me
          - /actuator/**
          - /health
          - /heartbeat
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
```

          
          
          
An finally......the problem resource server

QueryCommandServer:
================================================

```
scheme: http
hostname: 192.168.85.60
reverse-proxy-port: 7080
reverse-proxy-uri: '${scheme}://${hostname}:${reverse-proxy-port}'
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/intrepid'
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
resource-server-port: 7084
audience: 

server:
  port: '${resource-server-port}'
  ssl:
    enabled: false
  reactive:
    session:
      cookie:
        name: 'SESSION_${spring.application.name}'


com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: '${issuer}'
          username-claim: '${username-claim-json-path}'
          authorities:
          - path: '${authorities-json-path}'
          #- path: $.resource_access.spring-addons-confidential.roles
          - path: $.resource_access.*.roles
          aud: '${audience}'
        resourceserver:
          permit-all:
          #- /api/v1/querymanagercommandservice/**
          - /actuator/**
          - /api/v1/querymanagercommandservice/me/**
          - /me
          - /v3/api-docs/**
          - /swagger-ui/**
          - /actuator/health/readiness
          - /actuator/health/liveness
        cors:
        - path: /api/v1/querymanagercommandservice/**
          allowed-origin-patterns: "*"
        - path: /querymanagercommandservice/**
          allowed-origin-patterns: "*"
        - path: /truc/**
          allowed-origin-patterns:
          - "http://localhost:4200"
          - "http://*.chose.com"  
```

and its REST API

```
    /**
     * Create a new query on the system.
     *
     * @param queryRequest the query to process
     * @return ResultDto the response entity
     * @throws Exception the exception
     */
    @PreAuthorize("hasAuthority('TEST')")
    public Mono<ResultDto> createQuery(@RequestBody CreateQueryRequestDto createQueryRequest) throws InterruptedException {

        logger.info("UserCommandController: createQuery called for user: " + createQueryRequest.getLastName());

        queryCounter.increment();

        return this.queryManagerCommandService.createQuery(createQueryRequest);

    }

```
