### ISSUE TITLE
Claims used as authorities source should be split on space and comma (and trimmed)

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#125]
**Describe the bug**
When `scope` claim (or `scp`) is used as source for authorities, space separated values are interpreted as a single value. It should not.

**Code sample**
```yaml
com:
  c4-soft:
    springaddons:
      security:
        issuers:
        - location: ${oauth2-issuer}
          username-claim: $['https://c4-soft.com/user']['name']
          authorities:
          - path: $.scope
            prefix: SCOPE_
```

**Expected behavior**
Each scope entry in the scope claim should be mapped to an individual `GrantedAuthority` (each prefixed with `SCOPE_` in the sample above)
