### ISSUE TITLE
Auto-configure (with application properties) additional parameters for authorization-code request

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#129]
**Is your feature request related to a problem? Please describe.**
Auth0 enforces the usage of audience, but Spring Boot client configuration offers nothing to that regard and I have to [customize the authorization request](https://docs.spring.io/spring-security/reference/servlet/oauth2/client/authorization-grants.html#_customizing_the_authorization_request) in Java code.

**Describe the solution you'd like**
Configure `audience` in application properties and have Spring Boot starters auto-configure the authorization request for me.

**Comment by ch4mpy** [comment]
Let's make this feature more generic and allow to add any parameters to the authorization-code request (not just Audience).

Here is sample for the target configuration (where `auth0-confidential-user` references an existing entry in `spring.security.oauth2.client.registration`):
```yaml
com:
  c4-soft:
    springaddons:
      security:
        client:
          authorization-request-params:
            auth0-confidential-user:
            - name: audience
              value: https://bff.demo.c4-soft.com
            - name: machin
              value: truc
            - name: machin
              value: chose
```
