### ISSUE TITLE
`@WithJwt` does not convert claims using `ConfigurableClaimSetAuthoritiesConverter` and path from configuration

### ISSUE THREAD

**Issue by andreasgerner** [ch4mpy/spring-addons#171]
**Describe the bug**
When using `@WithJwt`, the roles of my JWT-JSON-File are not picked up according to the configured JSON-Path in my configuration.
Further debugging showed me, that `ConfigurableClaimSetAuthoritiesConverter::convert` doesn't get called.

**Code sample**
Test Class:
```java
@AutoConfigureAddonsWebmvcResourceServerSecurity
public class UserServiceTest { 
	@Test
    @WithJwt("student.json")
    void shouldSaveUser() { ... }
}
```

student.json:
```json
{
	"resource_access": {
    	"client-name": {
     		"roles": [
       			"some-role"
      		]
    	}
  	},
}
```

application.yml (in test resources):
```yaml
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: https://some-issuer.com/auth/realms/master
            authorities:
              - path: $.resource_access.client-name.roles
```

**Expected behavior**
`Authentication` set in test has authority 'some-role'. Instead, authorities only include scopes.

**Comment by ch4mpy** [comment]
@andreasgerner can share your project or reproducer? What you are doing seems pretty close to what is done at several places in this repo (and others that I author), so it should work...

**Comment by andreasgerner** [comment]
I setup a [sample](https://github.com/andreasgerner/spring-addons-bug-sample) containing everything that should be needed to reproduce.

**Comment by ch4mpy** [comment]
@andreasgerner I found a few things to fix in your reproducer:
- the values in your `src/main/resources/application.yaml` should be resolved (use environment variables to replace this values when you start the program)
```yaml
oidc:
  issuer-url: https://some-issuer.com/auth/realms/master
  client-id: client-id
```
- the test resources override main application.properties and the `com.c4-soft.*` are lost => rename `src/test/resources/application.yaml` to `src/test/resources/application-test.yaml`
- the test itself is not a Spring test (you probably want to run a `@WithMckMvc` or `@SpringBootTest`, so decorate the test with what is relevant)
