### ISSUE TITLE
Doubled path-prefix by `SpringAddonsServerOAuth2AuthorizationRequestResolver`

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#182]
**Describe the bug**
When setting a `client-uri` with a path-prefix, this path is doubled in the built authorization URI

**Code sample**
```yaml
com:
  c4-soft:
    springaddons:
      oidc:
        client:
          client-uri: https://localhost:7080/bff
```

**Expected behavior**
The response to the authorization-code flow initiation should contain `Location` with a `redirect_uri` request parameter like `https://localhost:7080/bff/login/oauth2/code/quiz-bff` (not `https://localhost:7080/bff/bff/login/oauth2/code/quiz-bff`)
