### ISSUE TITLE
(Not a bug) Really excellent work!

### ISSUE THREAD

**Issue by teuber789** [ch4mpy/spring-addons#22]
I happened upon this repo while looking for a way to mock Keycloak tokens in Spring MVC controller tests. Your `WithMockKeycloakAuth` annotation worked like a charm and saved me a ton of hassle. Just wanted to post a little note saying thanks again and keep up the good work!

(This isn't exactly a bug...but I wasn't sure where else to put it :/ )

**Comment by ch4mpy** [comment]
@teuber789 much appreciated. Thanks.

**Comment by fintans** [comment]
@ch4mpy can this lib be used for full integration testing rather than unit tests with mockMVC?

**Comment by ch4mpy** [comment]
@fintans No, this libs won't be of any help for integration testing. 

Test libs in this repo are **not** producing base64 encoded JSON Web Tokens which are decoded, validated and turned into `Authentication` by Spring framework.

Instead, it is building `Authentication` instances (`KeycloakAuthenticationToken`, JwtAuthenticationToken`, `OidcAuthentication`, etc.) out of annotations, `RequestPostProcessor` (for `MockMvc`) or `WebTestClientConfigurer` (for `WebTestClient`)  and populates test security context with it.

## Why not producing actual JWTs and populating `Authorization` header with it?
- When testing other `@Compent` than `@Controller`, request context is not relevant (it's perfectly legit to test a `@Service` with a security context for a non-web app => no authorization header to set.
- I can't sign the token with authorization server private key.
- In unit tests, you don't really care about token validity (i.e. the token being expired or not having an expiration claim at all is most frequently acceptable).
- In unit tests, you don't care about the Authorisation header. All you might care is the test security context being populated with the right `Authentication` implementation and have some control over it's properties (granted authorities and others)

## How do I run my integration tests?
If doing integration tests, an authorization server should be accessible. 
- Write an utility class using any REST client to issue OAuth2 authentication requests (details depend mostly on the flows your authorisation server supports)
- get actual valid tokens issued by your authorization server and put it in your tests requests `Authorization` header.

**Comment by razeelmohammed** [comment]
The Spring Boot 3 Keyclock examples are a real life saver. Good work team.

**Comment by ch4mpy** [comment]
@razeelmohammed good to read. 

If you like the libs, please consider giving a star. Same for the people you work with.

Seams stupid, but reaching 150 stars could open the door to publishing on Baeldung and greatly widen users community.

**Comment by ch4mpy** [comment]
@lArtiquel it is a work in progress. Baeldung required 150 popularity (stars plus forks) before I could submit articles about this libs and I reached it last month.

I have submitted a tutorial about mocking OAuth2 identities during tests which is in review (this a rather long process with pretty strict editorial rules I have to learn and comply with).

I hope one about portable resource-server configuration will follow.

**Comment by JonasMArnold** [comment]
Gave this one a star as well! Saved me a lot of pain in many regards.

Thanks @ch4mpy for this great repository as well as your active StackOverflow presence!

**Comment by ch4mpy** [comment]
@JonasMArnold thank you for the positive feedback, it is always pleasant to read.

I was pretty busy at that moment with two major upgrades:
- load test claim-sets from JSON files and build test Authentication using the converter found in test configuration
- merge all Spring Boot starters into a single one and refresh properties structure

Please make sure you give those two a try, I'm sure it is worth the effort.

**Comment by Makintos** [comment]
Another star! Thank you @ch4mpy 

One question: BFF + multitenant dynamic, is it possible?

```yaml
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
            user-name-attribute: ${user-name-attribute}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope:
            - openid
            - profile
            - email
            - offline_access
            - roles
```
