### ISSUE TITLE
Failed Initialization of the InMemoryReactiveClientRegistrationRepository when combined with Spring Auth Server and Reverse Proxy

### ISSUE THREAD

**Issue by rodrigosomoza** [ch4mpy/spring-addons#233]
**The bug**
As many of the people that decided to use this library i started by following the baeldung tutorial https://www.baeldung.com/spring-cloud-gateway-bff-oauth2.

### Initial Setup 3 modules:
- Spring Gateway
- Spring Oauth2 Authorization Server
- Spring Oauth2 Resource

### Current Setup:
- Spring Gateway with Spring addons dependency
- Spring Oauth2 Authorization Server
- Spring Oauth2 Resource
- Nginx Reverse Proxy in a docker container

From here everything was working fine, then i added the spring addons dependency with a nginx reverse proxy. The issue happens when the /auth/.well-known/oauth-authorization-server endpoint get accessed via the reverse proxy. The issuer is equal to http://localhost instead of this pattern: {scheme}://{reverse-proxy-uri}/auth. I assume there is some kind of issuer validation. Before adding the reverse proxy the gateway was accessing the auth server resulting into the issuer value matching on both sides.

-----------------------------------------------------------------------------------------------------

**Code sample**

### The Nginx config:
```
events {
    worker_connections 1024;
}

http {

    map $external_ip $external_ip {
        default "$EXTERNAL_IP";
    }

    server {
        listen 80;

        # Route for any path that starts with /auth (e.g., /auth, /auth/login, /auth/*)
        location /auth/ {
            rewrite ^/auth(/.*)$ $1 break;
            proxy_pass http://host.docker.internal:8484;
            proxy_set_header Host $host:${external_ip}/auth;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /auth {
            rewrite ^/auth$ / break;
            proxy_pass http://host.docker.internal:8484;
        }

        location ~ ^((/bff(/.*)?)|(/login(/.*)?)|(/oauth2(/.*)?)|(/logout)|(/login-options))$ {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```

### The Gateway configuration:

```yaml
gateway-port: 8080

server:
  port: ${gateway-port}


client-id: authorization-code-client
client-secret: <secret>
client-name: gateway-code-consent-flow


scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
auth-server-prefix: /auth
issuer-uri: ${reverse-proxy-uri}${auth-server-prefix}

spring:
  application:
    name: ms_gateway
  security:
    oauth2:
      client:
        registration:
          spring:
            client-id: ${client-id}
            client-secret: ${client-secret}
            client-name: ${client-name}
            provider: spring
            scope:
              - openid
              - profile
              - user.read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: authorization_code
        provider:
          spring:
            issuer-uri: ${issuer-uri}

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer-uri}
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        client:
          client-uri: ${reverse-proxy-uri}${gateway-prefix}
          security-matchers: ${client-security-matchers}
          permit-all: ${client-permit-all}
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
        resourceserver:
          permit-all: ${resource-server-permit-all}
```

Is the Issuer validations done by the spring addons lib? like it does with the resource server audience property?
