### ISSUE TITLE
Circular spring bean dependency when using `spring-addons` to create http client for spring oauth2 client

### ISSUE THREAD

**Issue by clutcher** [ch4mpy/spring-addons#254]
**Describe the bug**
 
Looks like there is a circular dependency when using `spring-addons` to create http client, used by `spring-boot-starter-oauth2-client` and `spring-boot-starter-web`.

**Code sample**

Zip with minimal gradle project:
[bug.zip](https://github.com/user-attachments/files/19450027/bug.zip)

**Expected behavior**
No circular dependency.

**Comment by ch4mpy** [comment]
It looks like the circular dependency is due to how `spring-boot-starter-oauth2-client` builds the `DefaultRefreshTokenTokenResponseClient` it injects into the default `OAuth2AuthorizedClientProvider`. So to break this circular dependency, you'll have to define this provider by yourself, as done in [the documentation snippet I linked in the other issue](https://github.com/ch4mpy/spring-addons/tree/master/spring-addons-starter-oidc#how-to-configure-the-authorized-client-manager-to-go-through-an-http-proxy), but as you're not using `spring-addons-starter-oidc`, using a `DelegatingOAuth2AuthorizedClientProvider` instead of spring-addons impl.

Here is a working conf without `spring-addons-starter-oidc`:
```java
@Configuration
public class BugConfiguration {

  ClientCredentialsOAuth2AuthorizedClientProvider clientCredentialsTokenResponseClientProvider(
      RestClient oauth2Client) {
    final var clientProvider = new ClientCredentialsOAuth2AuthorizedClientProvider();
    RestClientClientCredentialsTokenResponseClient client =
        new RestClientClientCredentialsTokenResponseClient();
    client.setRestClient(oauth2Client);
    clientProvider.setAccessTokenResponseClient(client);
    return clientProvider;
  }

  RefreshTokenOAuth2AuthorizedClientProvider refreshTokenResponseClientProvider(
      RestClient oauth2Client) {
    final var clientProvider = new RefreshTokenOAuth2AuthorizedClientProvider();
    RestClientRefreshTokenTokenResponseClient client =
        new RestClientRefreshTokenTokenResponseClient();
    client.setRestClient(oauth2Client);
    clientProvider.setAccessTokenResponseClient(client);
    return clientProvider;
  }

  @Bean
  RestClient oauth2Client(
      @Qualifier("oauth2ClientBuilder") RestClient.Builder oauth2ClientBuilder) {
    return oauth2ClientBuilder.messageConverters((messageConverters) -> {
      messageConverters.clear();
      messageConverters.add(new FormHttpMessageConverter());
      messageConverters.add(new OAuth2AccessTokenResponseHttpMessageConverter());
    }).defaultStatusHandler(new OAuth2ErrorResponseErrorHandler()).build();
  }

  @Bean
  OAuth2AuthorizedClientProvider oauth2AuthorizedClientProvider(
      InMemoryClientRegistrationRepository clientRegistrationRepository, RestClient oauth2Client) {
    return new DelegatingOAuth2AuthorizedClientProvider(
        clientCredentialsTokenResponseClientProvider(oauth2Client),
        refreshTokenResponseClientProvider(oauth2Client));
  }

}
```
With:
```yaml
spring:
  application:
    name: bug
  security:
    oauth2:
      client:
        registration:
          hybris:
            authorization-grant-type: test
            client-id: quiz-admin
            client-secret: secret
        provider:
          hybris:
            issuer-uri: https://mc-ch4mp.local/auth/realms/quiz
com:
  c4-soft:
    springaddons:
      rest:
        client:
          oauth2-client:
            expose-builder: true
            http:
              client-http-request-factory-impl: HTTP_COMPONENTS
              ssl-certificates-validation-enabled: false
```
Mind the `expose-builder: true` to override the default message converters and status handler for the client used to call the authorization server's token endpoint.

I'm not sure that there is anything I can do here to work around how the "official" starter resolves the beans it needs to build its default `OAuth2AuthorizedClientProvider`. 

As a side note, it seems surprising to configure a refresh token provider without an authorization code provider (tokens obtained with client credentials are not refreshed: to get new tokens, the client credentials flow is used again).
