### ISSUE TITLE
Configurable message converters

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#257]
**Is your feature request related to a problem? Please describe.**
Under some circumstances, the `RestClient` & `WebClient` default message converters are not suitable. A sample is when talking to the token endpoint of an OAuth2 resource server.

Same observation for the error message handlers.

**Describe the solution you'd like**
A way to list the message converters `spring-addons-starter-rest` auto-configures `RestClient` or `WebClient` with.

**Describe alternatives you've considered**
Expose builders instead of `RestClient` or `WebClient` bean and manually override message converters, but this is a bit cumbersome.

**Additional context**
We have no guarantee that there will always be no-arg constructor for message converters, and it isn't a functional interface. So, the best that we can do here is probably to provide a list of message converter beans, which application code would have to define one way or the other. The default converters would be overridden only when this list isn't left empty in properties.

**Comment by ch4mpy** [comment]
This does not look like a spectacular feature.

To illustrate what it could look like in the case of a `RestClient` used to call the token endpoint of an OAuth2 authorization server:
#### Before
```yaml
com:
  c4-soft:
    springaddons:
      rest:
        client:
          token-client:
            expose-builder: true
```
```java
@Configuration
public class RestConfiguration {

  @Bean
  RestClient oauth2Client(RestClient.Builder oauth2ClientBuilder) {
    return oauth2ClientBuilder.messageConverters((messageConverters) -> {
      messageConverters.clear();
      messageConverters.add(new FormHttpMessageConverter());
      messageConverters.add(new OAuth2AccessTokenResponseHttpMessageConverter());
    }).defaultStatusHandler(new OAuth2ErrorResponseErrorHandler()).build();
  }
}
```
#### After
```yaml
com:
  c4-soft:
    springaddons:
      rest:
        client:
          token-client:
            expose-builder: true
            message-converter-beans:
            - defaultFormHttpMessageConverter
            - defaultOAuth2AccessTokenResponseHttpMessageConverter
            default-status-handler: defaultOAuth2ErrorResponseErrorHandler
```
```java
@Configuration
public class RestConfiguration {

  @Bean
  FormHttpMessageConverter defaultFormHttpMessageConverter() {
return new FormHttpMessageConverter();
  }

  @Bean
  OAuth2AccessTokenResponseHttpMessageConverter defaultOAuth2AccessTokenResponseHttpMessageConverter() {
return new OAuth2AccessTokenResponseHttpMessageConverter();
  }

  @Bean
  OAuth2ErrorResponseErrorHandler defaultOAuth2ErrorResponseErrorHandler() {
    return new new OAuth2ErrorResponseErrorHandler();
  }
}
```
