### ISSUE TITLE
CWE-601 with post login/logout URIs

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#267]
### Discussed in https://github.com/ch4mpy/spring-addons/discussions/266

<div type='discussions-op-text'>

<sup>Originally reported by @thomas-seag in an email on April 29, 2025</sup>
I recently used the `post_login_success_uri` parameter with `oauth2Login` authorization request, and discovered that it can redirect to any domain, meaning that my backend is vulnerable to _open redirect_:
- CWE-601: https://cwe.mitre.org/data/definitions/601.html
- https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
- https://developers.google.com/search/blog/2009/01/open-redirect-urls-is-your-site-being
</div>

**Comment by ch4mpy** [comment]
The proposed solution is to whitelist the allowed redirection URIs (post login success, post login failure, post logout) with regular expressions in application properties. For instance:
```yaml
backend: https://localhost
com:
  c4-soft:
    springaddons:
      oidc:
        client:
          client-uri: ${backend}/bff
          post-login-allowed-uri-patterns:
          - ${backend}/ui/.*
          - /ui/.*
          post-login-redirect-path: /ui/greet
          post-logout-allowed-uri-patterns:
          - ${backend}/ui/.*
          - /ui(/.*)?
          post-logout-redirect-path: /ui/
```

To limit the impact on existing apps, the default values would allow all redirections without an authority (just a path) or with the same authority as the `client-uri` property (if it has one). As a reminder, the authority of a URI is `${scheme}://${host}:${port}`.

The `post-login-allowed-uri-patterns` and `post-logout-allowed-uri-patterns` properties would contain lists of strings, each compiled to a `java.util.regex.Pattern`.

The application properties defining the redirection URI when none is provided with the authorization request (`post-login-redirect-host`, `post-login-redirect-path`, `post-logout-redirect-host`, and `post-logout-redirect-path`) would be checked at startup, throwing an exception in case of a mismatch with allowed patterns.

The post login/logout URIs provided at runtime by the frontend as headers or request params in the authorization or logout requests would throw an exception mapped to a `403` in case of a mismatch with allowed patterns.
