### ISSUE TITLE
id-token exposure

### ISSUE THREAD

**Issue by Karek-MA** [ch4mpy/spring-addons#270]
**Describe the bug**
I'm using the bff design pattern following your great tutorial and when initiating the logout from my angular app I can see the id-token exposed in the response header "Location"

**Expected behavior**
Hide the id-token on redirection

**Comment by ch4mpy** [comment]
Hi,

What you ask is not possible: most OpenID Providers require the ID token to be provided with the RP-Initiated Logout request (even if in the spec it is flagged as _"recommended"_ and not _"required"_). 

Anyhow, the ID token was issued by the OP, which keeps a copy of it. Sending it back is not a security issue.

**Comment by Karek-MA** [comment]
I got you,
Thank you very much

**Comment by Karek-MA** [comment]
@ch4mpy Hey, sorry to bother you again, and thanks a lot for your great tutorial on the BFF design pattern with Spring Cloud — it’s been really helpful for me.

I’ve been able to get the setup working fine in dev with the following gateway configuration:
```

security:
  oauth2:
    client:
      provider:
        auth-server:
          issuer-uri: ${issuer}
      registration:
        auth-server:
          provider: auth-server
          authorization-grant-type: authorization_code
          client-id: ${client-id}
          client-secret: ${client-secret}
          scope: openid, offline_access

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
            - /login/**
            - /oauth2/**
            - /logout
          permit-all:
            - /login/**
          csrf: cookie-accessible-from-js
          use-id-token-hint: false
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED

```

In dev, I serve the SPA, the auth server, and the gateway all via Nginx, and everything works well.

When I moved to production, though, I hit a roadblock. I have 2 instances each (SPA, auth servers, gateways) with load balancing between them via F5. The issue is that I can’t expose the gateway in the frontend layer, so I can’t provide it the issuer URI from the reverse proxy directly.

I tried splitting browser-facing endpoints (like /authorize) to go through the proxy while letting internal calls (like /token) go directly to the auth servers. With this, login works, but logout does not.

I saw one of your comments on Stack Overflow where you said:

“the frontend sending this request must be served from the same host as the RP.”

From this I take it that the gateway must be in the frontend layer for proper logout handling. But if so, wouldn’t that raise security concerns since the gateway becomes directly exposed?

Could you please share your advice on the best practice for this scenario? Should I expose the gateway in the frontend layer or open an ACL to the F5 frontend load balancer (behind the reverse proxy), or is there a safer architectural alternative you’d recommend for handling login and  logout properly with load-balanced auth servers and gateways?

Thanks again for your guidance 🙏

**Comment by ch4mpy** [comment]
I don't know which StackOverflow comment you refer to, but I probably meant that due to session cookies' security, the browser must see the frontend assets and the BFF as "same-site". 

In [the Baeldung article](https://www.baeldung.com/spring-cloud-gateway-bff-oauth2), I use an Nginx reverse proxy in front of both the Nginx server (or dev server) dedicated to the frontend and the BFF. Working alternatives could be:
- using the same Nginx to serve the frontend assets and route requests to the BFF
- serve the front-end assets from the static resources of the Spring BFF
- use the frontend dev server's proxy configuration to route requests to the BFF (and one of the solutions above for prod)

From the browser's point of view, regardless of the solutions, all resources are served with the same origin, which is the easiest way to ensure that the "same-site" policy is satisfied.

To achieve the same with your prod configuration, configure the `client-uri` to point to the unique backend's entrypoint for all resources: the load-balancer.

As a side note, be careful that an application with `oauth2Login` is stateful. So, when spawning several instances, the session data should be shared between all. The usual solution for that is Redis with [Spring Session](https://spring.io/projects/spring-session). The user state is stored in session (whether he's logged in or not, his identity, the OAuth2 tokens, ...). If the session data is not shared across instances, we can easily anticipate issues when a user logs in on an instance and is then load-balanced to another (which will happen for sure if the instance he first used is not available anymore).

**Comment by Karek-MA** [comment]
Thank you for your continued support.

I’m currently facing a challenge with my setup — specifically, the placement of the BFF within the backend layer. The BFF is accessible through the entry point (the load balancer f5), which works fine for external access. However, when the BFF attempts to fetch the well-known configuration or call the /token endpoint, it  uses the load balancer f5 as well.

This creates a problem since it requires an ACL from the BFF to the load balancer, and our security team does not allow that. I’m wondering — is this truly a security concern, or is there a recommended approach to handle such internal calls more securely?

To work around this, I tried keeping the issuer as an internal call and configuring the authorization URI to use the load balancer  (https://lb.../auth), which forwards requests to the authorization server. With this setup, login works properly, but logout does not.

Regarding session consistency between my authorization servers, I’m using ip_hash in the NGINX reverse proxy, and it seems to handle session stickiness correctly.

Here’s an overview of my current architecture:

Frontend Layer:

Two identical VMs hosting the Angular app and an NGINX reverse proxy.

NGINX proxies:

/ui → Angular app

/auth → Authorization Server

/bff → BFF service


Load balancing method:

Least connections for most routes.

ip_hash for the /auth route to ensure session persistence.



Backend Layer:

Two BFF instances configured with issuer-uri pointing to the entry point (F5 load balancer).

This causes the issue, as the BFF calls the authorization server through the F5 instead of directly.


Two authorization server instances.

Both BFF and authorization servers are in the same VLAN (backend layer).



I’d really appreciate your input on whether there’s a better way to configure this so the BFF can interact with the authorization server without violating security restrictions or breaking session handling.

**Comment by Karek-MA** [comment]
Thank you so much for mentioning the internal DNS solution!
I set up an internal NGINX load balancer pointing to the two Auth Server instances and resolved the internal IPs to the same domain name in the /etc/hosts file — and it worked perfectly.
I also use ip_hash for load balancing

```
upstream auth_servers {
        ip_hash;
        server 172.11.77.18:8080 max_fails=3 fail_timeout=30s;
        server 172.11.77.19:8080 max_fails=3 fail_timeout=30s;
    }
```
I also noticed you mentioned the session consistency issue again. I think I haven’t run into it yet because the environment is still handling relatively low traffic, as you said. Could you please point me in the right direction for how to properly handle it in a production setup?

Here’s what I’ve done so far:

Auth Server:

Configured JWKSource<SecurityContext> to generate a consistent key ID based on the key fingerprint.

Using Spring Session for session management.

BFF Gateway:
Using Redis for session management with the following configuration:

```
spring:
  session:
    store-type: redis
    timeout: 3600
    redis:
      save-mode: on_set_attribute
      namespace: bff:sessions
      cleanup-cron: "0 0 * * * *"
  servlet:
    session:
      cookie:
        name: BFFSESSION
        http-only: true
        same-site: strict
        max-age: 3600
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      connect-timeout: 2000ms
```


Thanks again for your help
